### PR TITLE
Symfony 4 Support

### PR DESCRIPTION
**Pull request by roissard**
Changed the way the bundle is initialized and use dependency injection where container was used.

Bonus: the Logger initialization has been fixed, the logic was residing in the VoryxThruwayExtension, which cause the init to be valid only when DI was recompiling.

### CODE REVIEW

**Comment by davidwdan** [comment]
Does the README need to be updated?

**Comment by roissard** [comment]
I've just updated the README.

**Comment by davidwdan** [comment]
A couple of things:

1. It looks like `symfony/annotations-pack` needs to be added as a dependency, since it's not included with the default install of symfony. 
2. Also , `thruway/pawl-transport` needs to be added as a dependency.
3. `addCritical()` isn't part of the logger PSR, should it just be `critical()`?
4. Some services need to be set to public:  `voryx.thruway.loop`, `voryx.thruway.resource.mapper` ie:`<service id="voryx.thruway.loop" class="React\EventLoop\LoopInterface" public="true">`.  When we drop 2.x support, we'll be able to inject those services directly into the commands.
5.  In symfony 4 there is no longer a default bundle, so the user either needs to specify which files to include, or we'll need to automatically detect controllers.  For the time being you can just update the README with a note about that, until we automatically detect the controllers.

**Comment by roissard** [comment]
Hi,
1. When I install Symfony 4 following [official instructions](http://symfony.com/doc/current/setup.html) I can see that the doctrine/annotations package is installed (through symfony/orm-pack). Maybe you use a different installation process.
2. Ok, it's been added
3. Ok, fixed
4. Ok, done
5. I've added a note on how to indicate Symfony 4 to retrieve some workers.

**Pull request merged**
