### PR TITLE
Add Authorization Manager

### PR DESCRIPTION
**Pull request by AchilleAsh**
Implement the Authorization Manager and add the documentation to use it
I hope my DI is suitable, it works but maybe there is a better way to inject it

### CODE REVIEW

**Comment by davidwdan** [comment]
Thanks @AchilleAsh I'll take a look at this.  Is there any reason why you couldn't use the default AuthorizationManager?

My long term plan is allow you to add Authorization through annotations and yml configs.

**Comment by AchilleAsh** [comment]
In fact when testing the Thruway bundle I found no way to implement an authorization check, then I found this issue https://github.com/voryx/Thruway/issues/41 thus I chose to implement the Interface. But it's true that the Interface is not available in the dev-master branch of Thruway ; Should I extend the AuthorizationManager instead ? (if this is what you meant)

**Comment by davidwdan** [comment]
@AchilleAsh It should be pretty straight forward to implement with the current AuthorizationManager, if you need to authorize by role not authId.

I'll work up an example when I get a chance.

**Comment by AchilleAsh** [comment]
@davidwdan I've seen the auth by role indeed, but I needed an authorization by Authid: for example private messages are published in a channel identified by the UserID, thus I want to authorize only session with this corresponding UserID ( = my AuthID) to subscribe, and avoid any manipulated code to subscribe to others users channels and see private messages

**Pull request merged**
