### PR TITLE
Add "quote-binary" option

### PR DESCRIPTION
**Pull request by valepu**
Add "quote-binary" option to quote the PHP binary path in order to avoid failures in case it contains spaces

### CODE REVIEW

**Comment by youmad** [comment]
Maybe there is better to use [`escapeshellarg`](http://php.net/manual/en/function.escapeshellcmd.php) function?

**Comment by valepu** [comment]
i think that needs to be used regardless, but escapeshellarg does not do what my pull request does. I admit i realize right now i used the wrong word, i meant to make a "quote-binary" option not an "escape-binary". It has to be used when your php path contains spaces

**Comment by valepu** [comment]
New edit to use the correct word (quote and not escape)

**Comment by youmad** [comment]
I think that there is no need to add new option and better to wrap `PHP_BINARY` with `escapeshellarg` function that exists spec. for this purpose.
```
$ php -r "var_dump(escapeshellarg('/path/with s p a c e s'));"
Command line code:1:
string(24) "'/path/with s p a c e s'"
```

**Comment by valepu** [comment]
I'm terribly sorry, today i'm a bit sick and couldn't find anything about quoting paths with spaces in the function docs. then yes this is the most correct way to do it

**Comment by valepu** [comment]
closed in favor of https://github.com/voryx/ThruwayBundle/pull/70

**Pull request closed without merging**
